# Generated by Django 2.1.7 on 2019-02-12 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TempValues',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('val', models.IntegerField(default=0)),
                ('time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
